[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_SUPABASE_URL = "https://awnihpkyjmycjehgsnzo.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3bmlocGt5am15Y2plaGdzbnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NDg5NjUsImV4cCI6MjA3NjEyNDk2NX0.g6sR7yJoeOXXuJeDSflulUDwBwxbR-h_eoFVdvV37VI"

[[plugins]]
  package = "@netlify/plugin-nextjs"
